@baseUrl = http://localhost:3000
@v1api = {{baseUrl}}/api/v1
@contentType = application/json

### Probe /health
GET {{baseUrl}}/probes/health HTTP/1.1

###  PROBE /ready

GET {{baseUrl}}/probes/ready HTTP/1.1

### Sample / Auth 
GET {{v1api}}/samples/auth HTTP/1.1

### Sample / Auth With Payload
# @name login
POST {{v1api}}/samples/auth HTTP/1.1
Content-Type: {{contentType}}

{   
    "sub": "1234567890",
    "name": "test",
    "admin": true
}

### Sample / Protected With Auth
GET {{v1api}}/samples/protected/hello-world HTTP/1.1
Authorization: Bearer {{login.response.body.token}}